<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Test técnico SmartBoxTV</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
        <link rel="stylesheet" href="./assets/custom_bootstrap_950w/css/bootstrap.min.css">
        <link rel="stylesheet" href="./assets/custom_bootstrap_950w/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="./assets/main.css">
    </head>
    <body>
        <h1>Slim</h1>
        <div>a microframework for PHP</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?>
        <script type="text/javacript" src="./assets/custom_bootstrap_950w/js/bootstrap.min.js"></script>
    </body>
</html>
