<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Test técnico SmartBoxTV</title>
        <link href="//fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet">
        <link rel="stylesheet" href="assets/css/custom_bootstrap_950w/css/bootstrap.min.css">
        <link rel="stylesheet" href="assets/css/custom_bootstrap_950w/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="//ricostacruz.com/nprogress/nprogress.css">
        <link rel="stylesheet" href="assets/css/jquery.toast.css">
        <link rel="stylesheet" href="assets/css/theme.css">
        <link rel="stylesheet" href="assets/css/main.css">
    </head>
    <body>

        <div class="container-fluid text-center">
            <div class="row main-section">
                <div class="col-md-12">
                    <div class="container">
                        <img src="assets/img/icon.png" alt="Logo Nunchee Interactive">
                        <img src="assets/img/NuncheeInteractive.png" alt="Nunchee Interactive">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem eveniet eos doloremque. Ullam sed repellat quisquam magnam, magni, dolore eum corrupti? Eum, accusamus natus facilis mollitia excepturi dolores voluptates voluptatibus!</p>
                    </div>
                </div>
            </div>
            <div class="row second-section">
                <div class="container apps-container">
                    <h1>Nuestras Apps</h1>
                    <div class="col-md-4">
                        <img data-app="kunga" src="assets/img/kunga.png" alt="Kunga">
                    </div>
                    <div class="col-md-4">
                        <img data-app="fotoMiddle" src="assets/img/foto-middle.png" alt="Foto Middle" class="img-circle">
                    </div>
                    <div class="col-md-4">
                        <img data-app="directtv" src="assets/img/directtv.png" alt="Direct TV">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 parallax">

                </div>
            </div>
            <footer>
                <img src="assets/img/NuncheeInteractive_White.png" alt="Nunchee Interactive">
            </footer>
        </div>

        <!-- Login Modal -->
        <div class="modal fade" id="nunchee-modal" tabindex="-1" role="dialog" aria-labelledby="NuncheeModal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-body">
                <img id="login-app-brand" src="" alt="App logo">
              </div>
              <div class="modal-footer">
                <form class="nunchee-form">
                  <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="Username" required>
                  </div>
                  <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                  </div>
                  <button type="submit" class="btn">Enviar</button>
                </form>
              </div>
            </div>
          </div>
        </div>
        <script src="//code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="//ricostacruz.com/nprogress/nprogress.js"></script>
        <script src="assets/js/jquery.toast.js"></script>
        <script src="assets/js/main.js"></script>
    </body>
</html>
