<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Test técnico SmartBoxTV</title>
        <meta name="author" content="Nicolás Silva">
        <link href="//fonts.googleapis.com/css?family=Roboto:100,400" rel="stylesheet">
        <link rel="stylesheet" href="assets/css/custom_bootstrap_950w/css/bootstrap.min.css">
        <link rel="stylesheet" href="//ricostacruz.com/nprogress/nprogress.css">
        <link rel="stylesheet" href="assets/css/jquery.toast.css">
        <link rel="stylesheet" href="assets/css/theme.css">
        <link rel="stylesheet" href="assets/css/main.css">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <!-- main content -->
        <section class="container-fluid text-center">
            <div class="row main-section">
                <div class="col-md-12">
                    <div class="container">
                        <img src="assets/img/icon.png" alt="Logo Nunchee Interactive" class="logo">
                        <img src="assets/img/NuncheeInteractive.png" alt="Nunchee Interactive" class="brand-text">
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Autem eveniet eos doloremque. Ullam sed repellat quisquam magnam, magni, dolore eum corrupti? Eum, accusamus natus facilis mollitia excepturi dolores voluptates voluptatibus!</p>
                    </div>
                </div>
            </div>
            <div class="row second-section">
                <div class="container apps-container">
                    <h1>Nuestras Apps</h1>
                    <div class="col-md-4">
                        <div class="app">
                            <img data-app="kunga" src="assets/img/kunga.png" class="img-responsive" alt="Kunga">
                            <span class="name">KUNGA - Actitud Animal</span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <img src="assets/img/foto-middle.png" alt="Foto Middle" class="img-circle">
                    </div>
                    <div class="col-md-4">
                        <div class="app">
                            <img data-app="directtv" src="assets/img/directtv.png" class="img-responsive" alt="Direct TV">
                            <span class="name">DirectTV - TV Interactive</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 parallax"></div>
            </div>
        </section>
        <footer>
            <img src="assets/img/NuncheeInteractive_White.png" alt="Nunchee Interactive">
        </footer>
        <!-- Login Modal -->
        <div class="modal fade" id="nunchee-modal" tabindex="-1" role="dialog" aria-labelledby="nunchee-modal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-body">
                <img id="login-app-brand" src="" alt="App logo">
              </div>
              <div class="modal-footer">
                <form class="nunchee-form">
                  <div class="form-group">
                    <input type="text" class="form-control" name="username" placeholder="Username" required>
                  </div>
                  <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                  </div>
                  <button type="submit" class="btn">Enviar</button>
                </form>
              </div>
            </div>
          </div>
        </div>
        <script src="//code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <script src="//ricostacruz.com/nprogress/nprogress.js"></script>
        <script src="assets/js/jquery.toast.js"></script>
        <script src="assets/js/main.js"></script>
    </body>
</html>
